import React from "react";
import "./Report.css"; // CSS styles (same as I showed you earlier)

const UsersReport = ({ rows, generatedBy }) => {
  const now = new Date().toLocaleString();

  return (
    <div className="report-container">
      <header className="report-header">
        <div className="report-date">{now}</div>
        {/* <img
          src="https://upload.wikimedia.org/wikipedia/commons/3/3f/Placeholder_view_vector.svg"
          alt="Logo"
          className="report-logo"
        /> */}
        <h1>USERS REPORT</h1>
        <p>Generated from Users Table</p>
        <div className="report-period">
          <strong>Report Period:</strong> {new Date().toISOString().slice(0, 10)}
        </div>
      </header>

      <div className="report-table-container">
        <table className="report-table">
          <thead>
            <tr>
              <th>#</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Role</th>
              <th>Created At</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((user, i) => (
              <tr key={user._id}>
                <td>{i + 1}</td>
                <td>{user.firstName}</td>
                <td>{user.lastName}</td>
                <td>{user.email}</td>
                <td>{user.role}</td>
                <td>{new Date(user.createdAt).toLocaleDateString()}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <footer className="report-footer">
        <p>Generated by: {generatedBy}</p>
      </footer>
    </div>
  );
};

export default UsersReport;
