import React from "react";
import "./Report.css"; // CSS styles (same as I showed you earlier)
import govLogo from "../assets/gov.png";
import secondLogo from "../assets/sysLogo.png"; 
const UsersReport = ({ rows, generatedBy }) => {
  const now = new Date().toLocaleString();

  return (
    <div className="report-container">
    
      <header className="report-header">
        <div className="report-date">{now}</div>

        {/* Header content with flex */}
        <div className="report-header-content">
          <img src={govLogo} alt="Left Logo" className="report-logo left" />

          <div className="report-title-block">
            <h1>USERS REPORT</h1>
            <p>Generated from Issues Table</p>
            <div className="report-period">
              <strong>Report Period:</strong>{" "}
              {new Date().toISOString().slice(0, 10)}
            </div>
          </div>

          <img src={secondLogo} alt="Right Logo" className="report-logo right" />
        </div>
      </header>

      <div className="report-table-container">
        <table className="report-table">
          <thead>
            <tr>
              <th>#</th>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Role</th>
              <th>Created At</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((user, i) => (
              <tr key={user._id}>
                <td>{i + 1}</td>
                <td>{user.firstName}</td>
                <td>{user.lastName}</td>
                <td>{user.email}</td>
                <td>{user.role}</td>
                <td>{new Date(user.createdAt).toLocaleDateString()}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <footer className="report-footer">
        <p>Generated by: {generatedBy}</p>
      </footer>
    </div>
  );
};

export default UsersReport;
